// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "../ui.h"

void ui_view2_screen_init(void)
{
    ui_view2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_view2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_view2, lv_color_hex(0x351C53), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_view2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_view2, lv_color_hex(0x160F39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_view2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_view2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_view2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_linear1 = lv_bar_create(ui_view2);
    lv_bar_set_range(ui_linear1, -150, 250);
    lv_obj_set_width(ui_linear1, 700);
    lv_obj_set_height(ui_linear1, 50);
    lv_obj_set_x(ui_linear1, 0);
    lv_obj_set_y(ui_linear1, -50);
    lv_obj_set_align(ui_linear1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_linear1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_linear1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_linear1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_linear1,
                                                                                              lv_obj_get_style_pad_right(ui_linear1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_pid4 = lv_label_create(ui_view2);
    lv_obj_set_width(ui_pid4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pid4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pid4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pid4, "Boost");
    lv_obj_set_style_text_font(ui_pid4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_value4 = lv_label_create(ui_view2);
    lv_obj_set_width(ui_value4, 100);
    lv_obj_set_height(ui_value4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value4, 50);
    lv_obj_set_y(ui_value4, 0);
    lv_obj_set_align(ui_value4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_value4, "25.7 psi");
    lv_obj_set_style_text_font(ui_value4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);


}
