// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "../ui.h"

void ui_view3_screen_init(void)
{
    ui_view3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_view3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arc1 = lv_arc_create(ui_view3);
    lv_obj_set_width(ui_arc1, 150);
    lv_obj_set_height(ui_arc1, 150);
    lv_obj_set_x(ui_arc1, -250);
    lv_obj_set_y(ui_arc1, 0);
    lv_obj_set_align(ui_arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arc1, 0, 400);
    lv_arc_set_value(ui_arc1, 50);
    lv_arc_set_bg_angles(ui_arc1, 200, 340);
    lv_obj_set_style_arc_width(ui_arc1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc1, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_value5 = lv_label_create(ui_view3);
    lv_obj_set_width(ui_value5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value5, -250);
    lv_obj_set_y(ui_value5, 0);
    lv_obj_set_align(ui_value5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value5, "52");
    lv_obj_set_style_text_font(ui_value5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_value5, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(ui_value5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(ui_value5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gauge4 = lv_obj_create(ui_view3);
    lv_obj_remove_style_all(ui_gauge4);
    lv_obj_set_width(ui_gauge4, 100);
    lv_obj_set_height(ui_gauge4, 100);
    lv_obj_set_x(ui_gauge4, 0);
    lv_obj_set_y(ui_gauge4, -30);
    lv_obj_set_align(ui_gauge4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_gauge4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_gauge4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gauge4, lv_color_hex(0x9A9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gauge4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gauge4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_gauge4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_gauge4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_gauge4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_gauge4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);



}
