// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "../ui.h"

void ui_View1_screen_init(void)
{
    ui_View1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_View1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_View1, &ui_img_galaxy_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Guage1 = lv_image_create(ui_View1);
    lv_image_set_src(ui_Guage1, &ui_img_gauge125_png);
    lv_obj_set_width(ui_Guage1, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_Guage1, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_Guage1, -250);
    lv_obj_set_y(ui_Guage1, -90);
    lv_obj_set_align(ui_Guage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Guage1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Guage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Gauge2 = lv_image_create(ui_View1);
    lv_image_set_src(ui_Gauge2, &ui_img_gauge125_png);
    lv_obj_set_width(ui_Gauge2, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_Gauge2, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_Gauge2, 0);
    lv_obj_set_y(ui_Gauge2, -90);
    lv_obj_set_align(ui_Gauge2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gauge2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Gauge2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Gauge3 = lv_image_create(ui_View1);
    lv_image_set_src(ui_Gauge3, &ui_img_gauge125_png);
    lv_obj_set_width(ui_Gauge3, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_Gauge3, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_Gauge3, 250);
    lv_obj_set_y(ui_Gauge3, -90);
    lv_obj_set_align(ui_Gauge3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gauge3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Gauge3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle1 = lv_image_create(ui_View1);
    lv_image_set_src(ui_Needle1, &ui_img_needle125_png);
    lv_obj_set_width(ui_Needle1, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_Needle1, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_Needle1, -250);
    lv_obj_set_y(ui_Needle1, -90);
    lv_obj_set_align(ui_Needle1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Needle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle2 = lv_image_create(ui_View1);
    lv_image_set_src(ui_Needle2, &ui_img_needle125_png);
    lv_obj_set_width(ui_Needle2, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_Needle2, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_Needle2, 0);
    lv_obj_set_y(ui_Needle2, -90);
    lv_obj_set_align(ui_Needle2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Needle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle3 = lv_image_create(ui_View1);
    lv_image_set_src(ui_Needle3, &ui_img_needle125_png);
    lv_obj_set_width(ui_Needle3, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_Needle3, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_Needle3, 250);
    lv_obj_set_y(ui_Needle3, -90);
    lv_obj_set_align(ui_Needle3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Needle3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
