// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "../ui.h"

void ui_View2_screen_init(void)
{
    ui_View2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_View2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_View2, &ui_img_blue_purple_gradient_png, LV_PART_MAIN | LV_STATE_DEFAULT);



}
