// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
lv_obj_t * ui_Splash;
lv_obj_t * ui_SplashMessage;
// CUSTOM VARIABLES


// SCREEN: ui_View1
void ui_View1_screen_init(void);
lv_obj_t * ui_View1;
lv_obj_t * ui_Guage1;
lv_obj_t * ui_Gauge2;
lv_obj_t * ui_Gauge3;
lv_obj_t * ui_Needle1;
lv_obj_t * ui_Needle2;
lv_obj_t * ui_Needle3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_gauge[1] = {&ui_img_gauge125_png};
const lv_image_dsc_t * ui_imgset_needle[1] = {&ui_img_needle125_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Splash_screen_init();
    ui_View1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Splash);
}
