// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DigitalDash-U5-Disco

#ifndef _DIGITALDASH_U5_DISCO_UI_H
#define _DIGITALDASH_U5_DISCO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_SplashMessage;
// CUSTOM VARIABLES

// SCREEN: ui_View1
void ui_View1_screen_init(void);
extern lv_obj_t * ui_View1;
extern lv_obj_t * ui_Guage1;
extern lv_obj_t * ui_Gauge2;
extern lv_obj_t * ui_Gauge3;
extern lv_obj_t * ui_Needle1;
extern lv_obj_t * ui_Needle2;
extern lv_obj_t * ui_Needle3;
// CUSTOM VARIABLES

// SCREEN: ui_View2
void ui_View2_screen_init(void);
extern lv_obj_t * ui_View2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_flare_png);    // assets/Flare.png
LV_IMG_DECLARE(ui_img_galaxy_png);    // assets/Galaxy.png
LV_IMG_DECLARE(ui_img_gauge125_png);    // assets/gauge125.png
LV_IMG_DECLARE(ui_img_needle125_png);    // assets/needle125.png
LV_IMG_DECLARE(ui_img_blue_purple_gradient_png);    // assets/Blue Purple Gradient.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
